from core_ai.dao import DAO
from typing import List, Dict, Any
from datetime import datetime
import uuid


# ─────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────

def _risk_breakdown(daos: List[DAO]) -> Dict[str, int]:
    breakdown = {"high": 0, "medium": 0, "low": 0}
    for dao in daos:
        level = dao.risk_level if dao.risk_level in breakdown else "low"
        breakdown[level] += 1
    return breakdown


def _compliance_coverage(daos: List[DAO]) -> Dict[str, str]:
    """
    For each known clause, count how many DAOs satisfy it.
    Returns: { "FREE-AI Clause 3.1 ...": "18/24 decisions" }
    """
    clause_counts: Dict[str, int] = {}
    total = len(daos)

    for dao in daos:
        for tag in dao.compliance_tags:
            clause_counts[tag] = clause_counts.get(tag, 0) + 1

    return {
        clause: f"{count}/{total} decisions"
        for clause, count in clause_counts.items()
    }


def _violation_summary(daos: List[DAO]) -> Dict[str, int]:
    """
    Count how many times each violation type appeared across all DAOs.
    """
    violation_counts: Dict[str, int] = {}
    for dao in daos:
        for v in getattr(dao, "compliance_violations", []):
            violation_counts[v] = violation_counts.get(v, 0) + 1
    return violation_counts


def _overall_verdict(daos: List[DAO], flagged_count: int) -> str:
    total = len(daos)
    if flagged_count == 0:
        return "COMPLIANT — All decisions passed anomaly checks and RBI clause requirements."
    elif flagged_count <= total * 0.1:
        return f"MOSTLY COMPLIANT — {flagged_count} of {total} decisions flagged. Minor review required."
    elif flagged_count <= total * 0.3:
        return f"PARTIAL COMPLIANCE — {flagged_count} of {total} decisions flagged. Significant review required."
    else:
        return f"NON-COMPLIANT — {flagged_count} of {total} decisions flagged. Immediate remediation required."


# ─────────────────────────────────────────
# MAIN FUNCTION
# ─────────────────────────────────────────

def generate_report(session_id: str, daos: List[DAO]) -> Dict[str, Any]:
    """
    Takes all DAOs from a session and compiles them into a
    structured audit report dict. Frontend renders this into PDF.

    Called by backend when CCO clicks 'Generate Report'.
    """

    if not daos:
        return {
            "error": "No decisions found for this session.",
            "session_id": session_id,
        }

    total = len(daos)
    flagged = [dao for dao in daos if dao.risk_level in ("high", "medium")]
    clean = [dao for dao in daos if dao.risk_level == "low"]

    report = {
        # ── Identity ──────────────────────────────────
        "report_id": f"RPT-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}-{str(uuid.uuid4())[:6].upper()}",
        "session_id": session_id,
        "generated_at": datetime.utcnow().isoformat(),
        "agent_name": daos[0].agent_name if daos else "unknown",

        # ── Summary ───────────────────────────────────
        "session_summary": {
            "total_decisions": total,
            "flagged": len(flagged),
            "clean": len(clean),
            "risk_breakdown": _risk_breakdown(daos),
        },

        # ── Flagged Decisions (full detail) ───────────
        "flagged_decisions": [
            {
                "decision_id": dao.decision_id,
                "timestamp": dao.timestamp,
                "action_type": dao.action_type,
                "risk_level": dao.risk_level,
                "flag_reason": dao.flag_reason,
                "input": dao.input,
                "reasoning": dao.reasoning,
                "output": dao.output,
            }
            for dao in flagged
        ],

        # ── Compliance ────────────────────────────────
        "compliance_coverage": _compliance_coverage(daos),
        "violation_summary": _violation_summary(daos),

        # ── Verdict ───────────────────────────────────
        "verdict": _overall_verdict(daos, len(flagged)),

        # ── RBI Response Block ────────────────────────
        # This is what the CCO hands directly to the examiner
        "rbi_response_block": {
            "prepared_by": "AgentBridge Audit System",
            "framework": "RBI FREE-AI Framework (August 2025)",
            "session_covered": session_id,
            "total_agent_decisions_audited": total,
            "high_risk_decisions": len([d for d in daos if d.risk_level == "high"]),
            "compliance_verdict": _overall_verdict(daos, len(flagged)),
            "generated_at": datetime.utcnow().isoformat(),
            "note": (
                "This report was auto-generated by AgentBridge. "
                "All decisions are logged, timestamped, and mapped against "
                "the RBI FREE-AI Framework. Flagged decisions are listed above "
                "with full input, reasoning, output, and risk classification."
            ),
        },
    }

    return report